Add SVG support
MoonZoon/MoonZoon pull request #8
Opened 2021-05-15 00:08 UTC by flosse

2021-05-15 10:30 UTC, MartinKavik commented
Thanks, I'll try to look at it on Monday.

2021-05-16 10:48 UTC, MartinKavik commented
I don't know how to run the example. I see extra `index.html` and missing `Makefile.toml`. We should be able to run all examples the same way, described in [development.md](https://github.com/MoonZoon/MoonZoon/blob/main/docs/development.md#3-start-example)

2021-05-16 14:31 UTC, flosse commented
> I don't know how to run the example.

I just ran `../../target/debug/mzoon start`

> I see extra `index.html` and missing `Makefile.toml`. We should be able to run all examples the same way, described in [development.md](https://github.com/MoonZoon/MoonZoon/blob/main/docs/development.md#3-start-example)

I'm sorry, didn't read that :see_no_evil: ... it should work now

2021-05-16 15:33 UTC, MartinKavik requested changes
One review comment added. Once resolved I think we can merge it :)

2021-05-16 15:33 UTC, MartinKavik commented on crates/mzoon/src/main.rs
> +    fs::create_dir_all("backend/private").unwrap();
Please remove this line and add a `private` directory with `.gitignore` to the `svg` example. Build id, certificates and other stuff is stored in `private` and you don't want to accidentally push it to Git (for security reasons, unnecessary commit changes, incompatible certs among envs, etc.)

[private](https://github.com/MoonZoon/MoonZoon/tree/main/examples/counter/backend/private) in `counter` example

2021-05-16 21:06 UTC, MartinKavik commented
Ouch, sorry I forgot you've formatted the code and merged a new [PR](https://github.com/MoonZoon/MoonZoon/pull/10) 🙈 I hope rebasing won't be too painful 🤯

2021-05-17 10:23 UTC, MartinKavik approved these changes

2021-05-17 10:23 UTC, merged